apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: argocd-cert
  namespace: argocd
spec:
  dnsNames:
    - argotest.tk
  secretName: argocd-tls
  issuerRef:
    name: letsencrypt-cluster-issuer
    kind: ClusterIssuer