apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: api
  namespace: argocd
spec:
  project: local
  source:
    repoURL: 'https://github.com/ErgiKame/ArgoCD-VPS'
    path: api-manifests
    targetRevision: HEAD
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: api
  syncPolicy:
    automated: {}
    syncOptions:
      - CreateNamespace=true
    