apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: local
  namespace: argocd
spec:
  description: Local Environment
  sourceRepos:
  - '*'
  destinations:
  - namespace: '*'
    server: https://kubernetes.default.svc
  clusterResourceWhitelist:
  - group: '*'
    kind: '*'
  namespaceResourceWhitelist:
  - group: '*'
    kind: '*'