apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: selfsigned-ca-event-source
  namespace: argo-events
spec:
  isCA: true
  commonName: my-selfsigned-ca
  secretName: eventsource-tls
  privateKey:
    algorithm: ECDSA
    size: 256
  issuerRef:
    name: selfsigned-issuer
    kind: ClusterIssuer
    group: cert-manager.io