apiVersion: argoproj.io/v1alpha1
kind: EventSource
metadata:
  name: github
spec:
  service:
    ports:
    - port: 12000
      targetPort: 12000
  github:
    ArgoCD-VPS:
      owner: ErgiKame
      repository: ArgoCD-VPS
      webhook:
        endpoint: /
        port: "12000"
        method: POST
        url: https://argotest.tk/github
      events:
        - "*"
      active: true
      contentType: json