apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: argo-events

resources:
  - namespace.yaml
  - install.yaml
  - event-bus.yaml
  - event-source.yaml
  # - event-source-cert.yaml
  - event-source-ingress.yaml