apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: argocd-cert
  namespace: argo
spec:
  dnsNames:
    - workflows.argotest.tk
  secretName: argo-workflows-tls
  issuerRef:
    name: letsencrypt-cluster-issuer
    kind: ClusterIssuer