apiVersion: argoproj.io/v1alpha1
kind: EventSource
metadata:
  name: github
  namespace: argo
spec:
  service:
    ports:
    - port: 12000
      targetPort: 12000
  github:
    ArgoCD-VPS:
      owner: ErgiKame
      repository: ArgoCD-VPS
      webhook:
        endpoint: /github
        port: "12000"
        method: POST
        url: https://argotest.tk
      events:
        - "*"
      apiToken:
        name: github-access
        key: token
      active: true
      contentType: json