apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  name: build-container-image
  namespace: argo
  labels:
    workflows.argoproj.io/archive-strategy: "false"
spec:
  entrypoint: build
  serviceAccountName: workflow
  volumes:
  - name: kaniko-secret
    secret:
      secretName: regcred
      items:
        - key: .dockerconfigjson
          path: config.json
  templates:
  - name: build
    steps:
      - - name: build
          templateRef:
            name: build-container-image
            template: build-kaniko-git
            clusterScope: true
          arguments:
            parameters:
            - name: repo_url
              value: https://github.com/ErgiKame/ArgoCD-VPS
            - name: container_image
              value: ergikame/hyra-frontend
            - name: container_tag
              value: "testingKaniko"


# apiVersion: argoproj.io/v1alpha1
# kind: Workflow
# metadata:
#   generateName: workflow-template-hello-world-
# spec:
#   entrypoint: whalesay
#   templates:
#   - name: whalesay
#     steps:
#       - - name: call-whalesay-template
#           templateRef:
#             name: workflow-template-whalesay-template
#             template: whalesay-template
#           arguments:
#             parameters:
#             - name: message
#               value: "hello world"