apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: argo

resources:
  - namespace.yaml
  - argo-workflows.yaml
  - argo-workflows-ingress.yaml
  - github-event-source.yaml
  - github-event-source-ingress.yaml
  - workflows-rbac.yaml
  # - kaniko-workflow-template.yaml
  # - kaniko-workflow.yaml
  - kaniko-cluster-workflow.yaml
  - kaniko-sensor.yaml