apiVersion: argoproj.io/v1alpha1
  kind: Workflow
  metadata:
    generateName: workflow-kaniko
    namespace: argo-workflows
  spec:
    entrypoint: build
    serviceAccountName: argo-events-sa
    volumes:
    - name: regcred
      secret:
        secretName: regcred
        items:
          - key: .dockerconfigjson
            path: config.json
    - name: github-access
      secret:
        secretName: github-access
        items:
          - key: token
            path: token
          - key: user
            path: user
          - key: email
            path: email
    templates:
    - name: build
      dag:
        tasks:
        - name: build
          templateRef:
            name: container-image
            template: build-kaniko-git
            clusterScope: true
          arguments:
            parameters:
            - name: repo_url
              value: ""
            - name: repo_ref
              value: ""
            - name: repo_commit_id
              value: ""
            - name: container_image
              value: vfarcic/
            - name: container_tag
              value: ""