              apiVersion: argoproj.io/v1alpha1
              kind: Workflow
              metadata:
                name: build-image
                namespace: workflows
              spec:
                entrypoint: build
                serviceAccountName: workflow
                templates:
                  - dag:
                      tasks:
                        - arguments:
                            parameters:
                              - name: repo_url
                                value: https://github.com/ErgiKame/ArgoCD-VPS
                              - name: repo_ref
                                value: refs/heads/main
                              - name: repo_commit_id
                                value: HEAD
                              - name: container_image
                                value: ergikame/hyra-frontend
                              - name: container_tag
                                value: testingKaniko
                          name: build
                          templateRef:
                            clusterScope: true
                            name: container-image
                            template: build-kaniko-git
                    name: build
                volumes:
                  - name: regcred
                    secret:
                      items:
                        - key: .dockerconfigjson
                          path: config.json
                      secretName: regcred