apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: api-cert
  namespace: api
spec:
  dnsNames:
    - argotest.tk
  secretName: api-tls
  issuerRef:
    name: letsencrypt-cluster-issuer
    kind: ClusterIssuer